### ISSUE TITLE
Using SmallVector in other project and the license of this repository

### ISSUE THREAD

**Issue by marty1885** [thelink2012/SmallVector#1]
Hi thelink2012:

I've been searching for a implementation/stripped version of SmallVector for my [machine learning framework project](https://github.com/marty1885/Athena). May I use your SmallVector header in my project? If I can, what license of this repo?

Many thanks,
Martin

**Comment by thelink2012** [comment]
Hey Marty,

Yes, of course, you can use it. Given this code was stripped from LLVM, the license is [UIUC](https://en.wikipedia.org/wiki/University_of_Illinois/NCSA_Open_Source_License), which is a hybrid of MIT and BSD.

The full details of the license can be found on the [LICENSE](https://github.com/thelink2012/SmallVector/blob/master/LICENSE.TXT) file at the root of the repo.

Best Regards

**Comment by marty1885** [comment]
Hi,
Thanks!

Martin

Oops, I'm blind that I ignored the license file. :-) Sorry
